name: Make Linux Plugin

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build prereqs
        uses: docker/build-push-action@v3
        with:
          file: "{{defaultContext}}:net/grpc/gateway/docker/prereqs/Dockerfile"
          push: false
          tags: bourneid/grpc-web-demo:prereqs
      - name: Build server
        uses: docker/build-push-action@v3
        with:
          file: "{{defaultContext}}:net/grpc/gateway/docker/node_server/Dockerfile"
          push: false
          tags: bourneid/grpc-web-demo:node_server
      - name: Build server
        uses: docker/build-push-action@v3
        with:
          file: "{{defaultContext}}:net/grpc/gateway/docker/commonjs-client/Dockerfile"
          push: false
          tags: bourneid/grpc-web-demo:commonjs-client